# Script base was generated by ChatGPT.
import scipy.io
import numpy as np

# Load the data from the .mat file, select the specific variable
data = scipy.io.loadmat('your_data_file.mat', variable_names=['your_dataset_name'])

# Extract the selected dataset
dataset = data['your_dataset_name']

# Define the range of values to calculate the average over
start_index = 5
end_index = 10

# Calculate the average of the selected range
average = np.average(dataset[start_index:end_index+1])

# Create a new numpy array with the average value
average_array = np.array([average])

# Save the array to a .csv file using numpy
np.savetxt("average_data.csv", average_array, delimiter=",")